name: S3 Syncing and Cache Invalidation Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Use your bucket region here

      # Add your build steps here if needed
      # - name: Build Project
      #   run: yarn install && pm run-script build

      - name: Deploy content to S3 bucket
        run: aws s3 sync --delete s3://anjorin.me

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E18G28UVOQH9W3 --paths "/*"

